/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lebron;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class cadastro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(cadastro.class.getName());

    /**
     * Creates new form cadastro
     */
    public cadastro() {
        initComponents();
    }
    
    private Boolean validacoes(){
        if(TextFieldNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo nome deve ser preenchido");
            TextFieldNome.requestFocus();
            return false;
        }
        
        if(TextFieldCPF.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo CPF deve ser preenchido");
            TextFieldCPF.requestFocus();
            return false;
        }
        
        if(!RadioButtonGenMasc.isSelected() && !RadioButtonGenFem.isSelected()){
            JOptionPane.showMessageDialog(null, "Opção de genero não selecionada");
            TextFieldCPF.requestFocus();
            return false;
        }
        if(!CheckBoxTermos.isSelected()){
            JOptionPane.showMessageDialog(null, "Os termos precisam ser aceitos");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGen = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        TextFieldNome = new javax.swing.JTextField();
        LabelNome = new javax.swing.JLabel();
        LabelCPF = new javax.swing.JLabel();
        TextFieldCPF = new javax.swing.JTextField();
        ButtonSalvar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        LabelCity = new javax.swing.JLabel();
        ComboBoxCity = new javax.swing.JComboBox<>();
        LabelGen = new javax.swing.JLabel();
        RadioButtonGenMasc = new javax.swing.JRadioButton();
        RadioButtonGenFem = new javax.swing.JRadioButton();
        CheckBoxTermos = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cadastro de Cliente");

        TextFieldNome.addActionListener(this::TextFieldNomeActionPerformed);

        LabelNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelNome.setText("Nome");

        LabelCPF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelCPF.setText("CPF");

        ButtonSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonSalvar.setText("Salvar");
        ButtonSalvar.setToolTipText("");
        ButtonSalvar.addActionListener(this::ButtonSalvarActionPerformed);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        LabelCity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelCity.setText("Cidade");

        ComboBoxCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Campo Mourão", "Pindamonhamgaba", "Pintópolis", "Maringá", " " }));

        LabelGen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelGen.setText("Gênero");

        buttonGroupGen.add(RadioButtonGenMasc);
        RadioButtonGenMasc.setText("Masculino");

        buttonGroupGen.add(RadioButtonGenFem);
        RadioButtonGenFem.setText("Feminino");

        CheckBoxTermos.setText("Aceito os termos da utilização do treco");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(CheckBoxTermos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelGen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RadioButtonGenMasc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RadioButtonGenFem))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelCity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBoxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LabelNome)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TextFieldNome))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ButtonSalvar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton1)
                                    .addGap(122, 122, 122))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(LabelCPF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCPF)
                    .addComponent(TextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCity)
                    .addComponent(ComboBoxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelGen)
                    .addComponent(RadioButtonGenMasc)
                    .addComponent(RadioButtonGenFem))
                .addGap(33, 33, 33)
                .addComponent(CheckBoxTermos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSalvar)
                    .addComponent(jButton1))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNomeActionPerformed

    private void ButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarActionPerformed
        // TODO add your handling code here:
        boolean deu = validacoes();
        if (deu == true){
            JOptionPane.showMessageDialog(null, "Salvo com sucesso");
            System.exit(0);
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possível salvar");
        }
    }//GEN-LAST:event_ButtonSalvarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TextFieldNome.setText("Carlos");
        TextFieldCPF.setText("Casa do Caralho");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new cadastro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSalvar;
    private javax.swing.JCheckBox CheckBoxTermos;
    private javax.swing.JComboBox<String> ComboBoxCity;
    private javax.swing.JLabel LabelCPF;
    private javax.swing.JLabel LabelCity;
    private javax.swing.JLabel LabelGen;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JRadioButton RadioButtonGenFem;
    private javax.swing.JRadioButton RadioButtonGenMasc;
    private javax.swing.JTextField TextFieldCPF;
    private javax.swing.JTextField TextFieldNome;
    private javax.swing.ButtonGroup buttonGroupGen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
